volumes:
  nginx_logs:

services:
  frontend:
    build: ./frontend
    container_name: lb-ui-frontend
    ports:
      - "88:88"
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: lb-ui-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/nginx_proxy_configs:/data/nginx_proxy_configs
      - ./data/nginx_stream_configs:/data/nginx_stream_configs
      - ./data/certs:/data/certs
      - ./data/waf_rules:/data/waf_rules
      - nginx_logs:/var/log/nginx
      - ./data/config:/app/data/config
      - ./data/htpasswd:/data/htpasswd
      - ./data/licenses:/data/licenses
    env_file:
      - .env

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "10000-10100:10000-10100/tcp"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./data/nginx_proxy_configs:/etc/nginx/conf.d
      - ./data/nginx_stream_configs:/etc/nginx/stream.d
      - ./data/certs/letsencrypt:/etc/letsencrypt
      - ./data/certs/dummy:/etc/nginx/certs/dummy
      - ./data/htpasswd:/data/htpasswd
      - nginx_logs:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge